let state = {
    gear: null,
    gearSorted: null,

    guildBonuses: null,
    collectionPercentages: null,
    equppedGear: {
        slot1: null,
        slot2: null,
        slot3: null,
        slot4: null,
        slot5: null,
        slot6: null,
        slot7: null,
    },
    collectionGear: {
        slot1: null,
        slot2: null,
        slot3: null,
        slot4: null,
        slot5: null,
        slot6: null,
        slot7: null,
        slot8: null,
        slot9: null,
        slot10: null,
        slot11: null,
        slot12: null,
        slot13: null,
        slot14: null,
        slot15: null,
        slot16: null,
        slot17: null,
        slot18: null,
        slot19: null,
        slot20: null,
    },
    collectionGearFinalStats: {
        slot1: null,
        slot2: null,
        slot3: null,
        slot4: null,
        slot5: null,
        slot6: null,
        slot7: null,
        slot8: null,
        slot9: null,
        slot10: null,
        slot11: null,
        slot12: null,
        slot13: null,
        slot14: null,
        slot15: null,
        slot16: null,
        slot17: null,
        slot18: null,
        slot19: null,
        slot20: null,
    }
}

export default state